version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  users-api:
    image: tejirih/user-images:latest
    container_name: users-api
    environment:
      - JWT_SECRET=secret123
      - SERVER_PORT=8083
    ports:
      - "8083:8083"

  auth-api:
    image: tejirih/auth-image:latest
    container_name: auth-api
    environment:
      - AUTH_API_PORT=8081
      - USERS_API_ADDRESS=http://users-api:8083
      - JWT_SECRET=secret123
    ports:
      - "8081:8081"
    depends_on:
      - users-api

  todos-api:
    image: tejirih/todos-image:latest
    container_name: todos-api
    environment:
      - TODO_API_PORT=8082
      - JWT_SECRET=secret123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    ports:
      - "8082:8082"
    depends_on:
      - redis

  log-message-processor:
    image: tejirih/log-image:latest
    container_name: log-processor
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis

  frontend:
    image: tejirih/frontend:latest
    container_name: frontend
    environment:
      - PORT=8080
      - AUTH_API_ADDRESS=http://auth-api:8081
      - TODOS_API_ADDRESS=http://todos-api:8082
    ports:
      - "8088:80"
    depends_on:
      - auth-api
      - todos-api
