apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/TejiriH/HNG-Mircoservice-template.git
    targetRevision: HEAD
    path: k8s/deployment
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
