apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: tejirih/auth-image:latest
          ports:
            - containerPort: 8081
          env:
            - name: AUTH_API_PORT
              value: "8081"
            - name: USERS_API_ADDRESS
              value: "http://users-api:8083"
            - name: JWT_SECRET
              value: "secret123"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
spec:
  selector:
    app: auth-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
