apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: tejirih/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "8080"
            - name: AUTH_API_ADDRESS
              value: "http://auth-api:8081"
            - name: TODOS_API_ADDRESS
              value: "http://todos-api:8082"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: microservices
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

