apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: microservices
  labels:
    app: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: tejirih/user-images:latest
          ports:
            - containerPort: 8083
          env:
            - name: JWT_SECRET
              value: "secret123"
            - name: SERVER_PORT
              value: "8083"
---
apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: microservices
spec:
  selector:
    app: users-api
  ports:
    - port: 8083
      targetPort: 8083
